name: Publish to PyPI.org

on:
    schedule:
    - cron: '0 20 * * *'  # GMT 20 == GMT+8 04
    workflow_dispatch:
        # Manually trigger the release workflow, a version must be provided
        inputs:
            version:
                description: 'The version to release (e.g. v0.8.0), or leave it empty for nightly build'
                type: string
                required: false
jobs:
    pypi:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: python setup.py bdist_wheel --python-tag=py3
            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.PYPI_API_TOKEN }}
